name: leap
version: 1.4.0.8

dependencies:
  - base

library:
  exposed-modules: LeapYear
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - leap
      - hspec
