name: space-age
version: 1.1.0.5

dependencies:
  - base

library:
  exposed-modules: SpaceAge
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - space-age
      - hspec
