name: word-count
version: 1.2.0.6

dependencies:
  - base
  - containers
  - split

library:
  exposed-modules: WordCount
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - word-count
      - hspec
