name: luhn
version: 1.3.0.6

dependencies:
  - base

library:
  exposed-modules: Luhn
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - luhn
      - hspec
